class SuraModel {
  final int id;
  final String suraNameEN;
  final String suraNameAR;
  final int verses;

  SuraModel({
    required this.id,
    required this.suraNameEN,
    required this.suraNameAR,
    required this.verses,
  });

  static final List<SuraModel> suras = [
    SuraModel(id: 1, suraNameAR: "الفاتحه", suraNameEN: "Al-Fatiha", verses: 7),
    SuraModel(
      id: 2,
      suraNameAR: "البقرة",
      suraNameEN: "Al-Baqarah",
      verses: 286,
    ),
    SuraModel(
      id: 3,
      suraNameAR: "آل عمران",
      suraNameEN: "Aal-E-Imran",
      verses: 200,
    ),
    SuraModel(id: 4, suraNameAR: "النساء", suraNameEN: "An-Nisa'", verses: 176),
    SuraModel(
      id: 5,
      suraNameAR: "المائدة",
      suraNameEN: "Al-Ma'idah",
      verses: 120,
    ),
    SuraModel(
      id: 6,
      suraNameAR: "الأنعام",
      suraNameEN: "Al-An'am",
      verses: 165,
    ),
    SuraModel(
      id: 7,
      suraNameAR: "الأعراف",
      suraNameEN: "Al-A'raf",
      verses: 206,
    ),
    SuraModel(id: 8, suraNameAR: "الأنفال", suraNameEN: "Al-Anfal", verses: 75),
    SuraModel(
      id: 9,
      suraNameAR: "التوبة",
      suraNameEN: "At-Tawbah",
      verses: 129,
    ),
    SuraModel(id: 10, suraNameAR: "يونس", suraNameEN: "Yunus", verses: 109),
    SuraModel(id: 11, suraNameAR: "هود", suraNameEN: "Hud", verses: 123),
    SuraModel(id: 12, suraNameAR: "يوسف", suraNameEN: "Yusuf", verses: 111),
    SuraModel(id: 13, suraNameAR: "الرعد", suraNameEN: "Ar-Ra'd", verses: 43),
    SuraModel(id: 14, suraNameAR: "إبراهيم", suraNameEN: "Ibrahim", verses: 52),
    SuraModel(id: 15, suraNameAR: "الحجر", suraNameEN: "Al-Hijr", verses: 99),
    SuraModel(id: 16, suraNameAR: "النحل", suraNameEN: "An-Nahl", verses: 128),
    SuraModel(
      id: 17,
      suraNameAR: "الإسراء",
      suraNameEN: "Al-Isra",
      verses: 111,
    ),
    SuraModel(id: 18, suraNameAR: "الكهف", suraNameEN: "Al-Kahf", verses: 110),
    SuraModel(id: 19, suraNameAR: "مريم", suraNameEN: "Maryam", verses: 98),
    SuraModel(id: 20, suraNameAR: "طه", suraNameEN: "Ta-Ha", verses: 135),
    SuraModel(
      id: 21,
      suraNameAR: "الأنبياء",
      suraNameEN: "Al-Anbiya",
      verses: 112,
    ),
    SuraModel(id: 22, suraNameAR: "الحج", suraNameEN: "Al-Hajj", verses: 78),
    SuraModel(
      id: 23,
      suraNameAR: "المؤمنون",
      suraNameEN: "Al-Mu'minun",
      verses: 118,
    ),
    SuraModel(id: 24, suraNameAR: "النّور", suraNameEN: "An-Nur", verses: 64),
    SuraModel(
      id: 25,
      suraNameAR: "الفرقان",
      suraNameEN: "Al-Furqan",
      verses: 77,
    ),
    SuraModel(
      id: 26,
      suraNameAR: "الشعراء",
      suraNameEN: "Ash-Shu'ara",
      verses: 227,
    ),
    SuraModel(id: 27, suraNameAR: "النّمل", suraNameEN: "An-Naml", verses: 93),
    SuraModel(id: 28, suraNameAR: "القصص", suraNameEN: "Al-Qasas", verses: 88),
    SuraModel(
      id: 29,
      suraNameAR: "العنكبوت",
      suraNameEN: "Al-Ankabut",
      verses: 69,
    ),
    SuraModel(id: 30, suraNameAR: "الرّوم", suraNameEN: "Ar-Rum", verses: 60),
    SuraModel(id: 31, suraNameAR: "لقمان", suraNameEN: "Luqman", verses: 34),
    SuraModel(id: 32, suraNameAR: "السجدة", suraNameEN: "As-Sajda", verses: 30),
    SuraModel(
      id: 33,
      suraNameAR: "الأحزاب",
      suraNameEN: "Al-Ahzab",
      verses: 73,
    ),
    SuraModel(id: 34, suraNameAR: "سبأ", suraNameEN: "Saba", verses: 54),
    SuraModel(id: 35, suraNameAR: "فاطر", suraNameEN: "Fatir", verses: 45),
    SuraModel(id: 36, suraNameAR: "يس", suraNameEN: "Ya-Sin", verses: 83),
    SuraModel(
      id: 37,
      suraNameAR: "الصافات",
      suraNameEN: "As-Saffat",
      verses: 182,
    ),
    SuraModel(id: 38, suraNameAR: "ص", suraNameEN: "Sad", verses: 88),
    SuraModel(id: 39, suraNameAR: "الزمر", suraNameEN: "Az-Zumar", verses: 75),
    SuraModel(id: 40, suraNameAR: "غافر", suraNameEN: "Ghafir", verses: 85),
    SuraModel(id: 41, suraNameAR: "فصّلت", suraNameEN: "Fussilat", verses: 54),
    SuraModel(
      id: 42,
      suraNameAR: "الشورى",
      suraNameEN: "Ash-Shura",
      verses: 53,
    ),
    SuraModel(
      id: 43,
      suraNameAR: "الزخرف",
      suraNameEN: "Az-Zukhruf",
      verses: 89,
    ),
    SuraModel(
      id: 44,
      suraNameAR: "الدّخان",
      suraNameEN: "Ad-Dukhan",
      verses: 59,
    ),
    SuraModel(
      id: 45,
      suraNameAR: "الجاثية",
      suraNameEN: "Al-Jathiya",
      verses: 37,
    ),
    SuraModel(
      id: 46,
      suraNameAR: "الأحقاف",
      suraNameEN: "Al-Ahqaf",
      verses: 35,
    ),
    SuraModel(id: 47, suraNameAR: "محمد", suraNameEN: "Muhammad", verses: 38),
    SuraModel(id: 48, suraNameAR: "الفتح", suraNameEN: "Al-Fath", verses: 29),
    SuraModel(
      id: 49,
      suraNameAR: "الحجرات",
      suraNameEN: "Al-Hujurat",
      verses: 18,
    ),
    SuraModel(id: 50, suraNameAR: "ق", suraNameEN: "Qaf", verses: 45),
    SuraModel(
      id: 51,
      suraNameAR: "الذاريات",
      suraNameEN: "Adh-Dhariyat",
      verses: 60,
    ),
    SuraModel(id: 52, suraNameAR: "الطور", suraNameEN: "At-Tur", verses: 49),
    SuraModel(id: 53, suraNameAR: "النجم", suraNameEN: "An-Najm", verses: 62),
    SuraModel(id: 54, suraNameAR: "القمر", suraNameEN: "Al-Qamar", verses: 55),
    SuraModel(
      id: 55,
      suraNameAR: "الرحمن",
      suraNameEN: "Ar-Rahman",
      verses: 78,
    ),
    SuraModel(
      id: 56,
      suraNameAR: "الواقعة",
      suraNameEN: "Al-Waqi'a",
      verses: 96,
    ),
    SuraModel(id: 57, suraNameAR: "الحديد", suraNameEN: "Al-Hadid", verses: 29),
    SuraModel(
      id: 58,
      suraNameAR: "المجادلة",
      suraNameEN: "Al-Mujadila",
      verses: 22,
    ),
    SuraModel(id: 59, suraNameAR: "الحشر", suraNameEN: "Al-Hashr", verses: 24),
    SuraModel(
      id: 60,
      suraNameAR: "الممتحنة",
      suraNameEN: "Al-Mumtahina",
      verses: 13,
    ),
    SuraModel(id: 61, suraNameAR: "الصف", suraNameEN: "As-Saff", verses: 14),
    SuraModel(
      id: 62,
      suraNameAR: "الجمعة",
      suraNameEN: "Al-Jumu'a",
      verses: 11,
    ),
    SuraModel(
      id: 63,
      suraNameAR: "المنافقون",
      suraNameEN: "Al-Munafiqun",
      verses: 11,
    ),
    SuraModel(
      id: 64,
      suraNameAR: "التغابن",
      suraNameEN: "At-Taghabun",
      verses: 18,
    ),
    SuraModel(id: 65, suraNameAR: "الطلاق", suraNameEN: "At-Talaq", verses: 12),
    SuraModel(
      id: 66,
      suraNameAR: "التحريم",
      suraNameEN: "At-Tahrim",
      verses: 12,
    ),
    SuraModel(id: 67, suraNameAR: "الملك", suraNameEN: "Al-Mulk", verses: 30),
    SuraModel(id: 68, suraNameAR: "القلم", suraNameEN: "Al-Qalam", verses: 52),
    SuraModel(
      id: 69,
      suraNameAR: "الحاقة",
      suraNameEN: "Al-Haqqah",
      verses: 52,
    ),
    SuraModel(
      id: 70,
      suraNameAR: "المعارج",
      suraNameEN: "Al-Ma'arij",
      verses: 44,
    ),
    SuraModel(id: 71, suraNameAR: "نوح", suraNameEN: "Nuh", verses: 28),
    SuraModel(id: 72, suraNameAR: "الجن", suraNameEN: "Al-Jinn", verses: 28),
    SuraModel(
      id: 73,
      suraNameAR: "المزّمّل",
      suraNameEN: "Al-Muzzammil",
      verses: 20,
    ),
    SuraModel(
      id: 74,
      suraNameAR: "المدّثر",
      suraNameEN: "Al-Muddathir",
      verses: 56,
    ),
    SuraModel(
      id: 75,
      suraNameAR: "القيامة",
      suraNameEN: "Al-Qiyamah",
      verses: 40,
    ),
    SuraModel(
      id: 76,
      suraNameAR: "الإنسان",
      suraNameEN: "Al-Insan",
      verses: 31,
    ),
    SuraModel(
      id: 77,
      suraNameAR: "المرسلات",
      suraNameEN: "Al-Mursalat",
      verses: 50,
    ),
    SuraModel(id: 78, suraNameAR: "النبأ", suraNameEN: "An-Naba'", verses: 40),
    SuraModel(
      id: 79,
      suraNameAR: "النازعات",
      suraNameEN: "An-Nazi'at",
      verses: 46,
    ),
    SuraModel(id: 80, suraNameAR: "عبس", suraNameEN: "Abasa", verses: 42),
    SuraModel(
      id: 81,
      suraNameAR: "التكوير",
      suraNameEN: "At-Takwir",
      verses: 29,
    ),
    SuraModel(
      id: 82,
      suraNameAR: "الإنفطار",
      suraNameEN: "Al-Infitar",
      verses: 19,
    ),
    SuraModel(
      id: 83,
      suraNameAR: "المطفّفين",
      suraNameEN: "Al-Mutaffifin",
      verses: 36,
    ),
    SuraModel(
      id: 84,
      suraNameAR: "الإنشقاق",
      suraNameEN: "Al-Inshiqaq",
      verses: 25,
    ),
    SuraModel(id: 85, suraNameAR: "البروج", suraNameEN: "Al-Buruj", verses: 22),
    SuraModel(id: 86, suraNameAR: "الطارق", suraNameEN: "At-Tariq", verses: 17),
    SuraModel(id: 87, suraNameAR: "الأعلى", suraNameEN: "Al-A'la", verses: 19),
    SuraModel(
      id: 88,
      suraNameAR: "الغاشية",
      suraNameEN: "Al-Ghashiyah",
      verses: 26,
    ),
    SuraModel(id: 89, suraNameAR: "الفجر", suraNameEN: "Al-Fajr", verses: 30),
    SuraModel(id: 90, suraNameAR: "البلد", suraNameEN: "Al-Balad", verses: 20),
    SuraModel(id: 91, suraNameAR: "الشمس", suraNameEN: "Ash-Shams", verses: 15),
    SuraModel(id: 92, suraNameAR: "الليل", suraNameEN: "Al-Lail", verses: 21),
    SuraModel(id: 93, suraNameAR: "الضحى", suraNameEN: "Ad-Duha", verses: 11),
    SuraModel(id: 94, suraNameAR: "الشرح", suraNameEN: "Ash-Sharh", verses: 8),
    SuraModel(id: 95, suraNameAR: "التين", suraNameEN: "At-Tin", verses: 8),
    SuraModel(id: 96, suraNameAR: "العلق", suraNameEN: "Al-Alaq", verses: 19),
    SuraModel(id: 97, suraNameAR: "القدر", suraNameEN: "Al-Qadr", verses: 5),
    SuraModel(
      id: 98,
      suraNameAR: "البينة",
      suraNameEN: "Al-Bayyina",
      verses: 8,
    ),
    SuraModel(
      id: 99,
      suraNameAR: "الزلزلة",
      suraNameEN: "Az-Zalzalah",
      verses: 8,
    ),
    SuraModel(
      id: 100,
      suraNameAR: "العاديات",
      suraNameEN: "Al-Adiyat",
      verses: 11,
    ),
    SuraModel(
      id: 101,
      suraNameAR: "القارعة",
      suraNameEN: "Al-Qari'a",
      verses: 11,
    ),
    SuraModel(
      id: 102,
      suraNameAR: "التكاثر",
      suraNameEN: "At-Takathur",
      verses: 8,
    ),
    SuraModel(id: 103, suraNameAR: "العصر", suraNameEN: "Al-Asr", verses: 3),
    SuraModel(
      id: 104,
      suraNameAR: "الهمزة",
      suraNameEN: "Al-Humazah",
      verses: 9,
    ),
    SuraModel(id: 105, suraNameAR: "الفيل", suraNameEN: "Al-Fil", verses: 5),
    SuraModel(id: 106, suraNameAR: "قريش", suraNameEN: "Quraysh", verses: 4),
    SuraModel(
      id: 107,
      suraNameAR: "الماعون",
      suraNameEN: "Al-Ma'un",
      verses: 7,
    ),
    SuraModel(
      id: 108,
      suraNameAR: "الكوثر",
      suraNameEN: "Al-Kawthar",
      verses: 3,
    ),
    SuraModel(
      id: 109,
      suraNameAR: "الكافرون",
      suraNameEN: "Al-Kafirun",
      verses: 6,
    ),
    SuraModel(id: 110, suraNameAR: "النصر", suraNameEN: "An-Nasr", verses: 3),
    SuraModel(id: 111, suraNameAR: "المسد", suraNameEN: "Al-Masad", verses: 5),
    SuraModel(
      id: 112,
      suraNameAR: "الإخلاص",
      suraNameEN: "Al-Ikhlas",
      verses: 4,
    ),
    SuraModel(id: 113, suraNameAR: "الفلق", suraNameEN: "Al-Falaq", verses: 5),
    SuraModel(id: 114, suraNameAR: "الناس", suraNameEN: "An-Nas", verses: 6),
  ];
}
